spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  h2:
    console:
      enabled: true
server:
  servlet:
    session:
      timeout: 30m
      cookie:
        domain: owasp-guidelines-good.com
        path: /
    context-path: /good-example
